### PR TITLE
Fix WithConfig instances

### PR DESCRIPTION
**Pull request by CapacitorSet**
Discovered while fixing #402. ~~Not yet ready for merging, I'm waiting for feedback on the issue.~~

### CODE REVIEW

**Comment by nl5887** [comment]
Waiting for feedback if issue has been resolved?

**Comment by nl5887** [comment]
@sammynx could you verify?

**Comment by CapacitorSet** [comment]
Yes, I'm waiting for confirmation that they're actually unused (so that I know it's not a bug in WithConfig).

**Comment by sammynx** [comment]
The warning is correct, the values are unused. This is the issue. However when I tested this pull, the warning is gone for me. So it's hiding a problem now.

**Comment by sammynx** [comment]
I don't know how my config looked anymore, because I changed it a lot recently. I was working on this issue with smtp. There must have been a mixup with configs, because I can't recreate my issues from last comment.

Situation now:
on a build from master I get this warning
`honeytrap/server ▶ WARN 00a Unrecognized keys in configuration: [channel.file.filename]`
However it is using `channel.file.filename`

on a build from this PR I get no warnings.

So this is working for me now. Sorry for the confusion I made in earlier comments.


This is the config I used for this.
```
[listener]
type="socket"

[service.smtp]
type="smtp"
#host="smtp.mailer.org"
#name="HT SMTP-E v2.3.0.1b"
#banner-fmt='{{.Host}} {{.Name}} - Ready'
#users=[ ["root","root"], ["admin", "admin"] ]
#secrets=[ ["user", "password"] ]

[[port]]
port="tcp/8025"
services=["smtp"]

[channel.console]
type="console"

[channel.file]
type="file"
filename="/tmp/honeytrap.log"

[[filter]]
channel=["console", "file"]

[[logging]]
output = "stdout"
level = "debug"
```

**Comment by CapacitorSet** [comment]
Thank you for your feedback.

This PR is ready for merging, then.

**Comment by nl5887** [comment]
Merged, thanks!

**Pull request merged**
