### PR TITLE
config: fix agent config for Docker

### LINKED ISSUE #414: No public key when starting docker-compose script
I'm fairly new to this, sorry if it's just idiocy,  I compiled the Agent and followed the server install instructions. I'm running Ubuntu 16.04 and when I try to run the agent I can't because I don't have the public key.

When I run the following to start honeytrap server:

`docker-compose -f ./docker-compose-honeytrap.yml up`

I don't see the following message in the output per the documentation:
`honeytrap_1      | HoneyTrap Agent Server public key: <key>`

The only message I get referring to keys is:
`honeytrap_1      | 08:59:59.922 honeytrap/server  WARN 008 Unrecognized keys in configuration: [service.telnet.image service.telnet.server-name]`

When I look in here the following location, there appears to be no documentation:
[(http://docs.honeytrap.io/docs/concepts/framework/honeytrap-server/)](http://docs.honeytrap.io/docs/concepts/framework/honeytrap-server/)

The honeytrap server appears to initialize successfully: 

honeytrap_1      | 2018/08/10 08:59:59 Using config file /config/config.toml
honeytrap_1      | Honeytrap starting (bdmxxxxxxxxbcbgi0)... 
honeytrap_1      | Version: 2018-08-01T18:49:21Z (1b595a78e1da)
honeytrap_1      | 08:59:59.913 honeytrap/server ▶ DEBU 002 Using datadir: /data
honeytrap_1      | 08:59:59.917 honeytrap/server ▶ INFO 003 Configured service ssh-simulator (ssh-simulator)
honeytrap_1      | 08:59:59.918 honeytrap/server ▶ INFO 004 Configured service telnet (telnet)
honeytrap_1      | 08:59:59.918 honeytrap/server ▶ INFO 005 Configured port tcp/:8022
honeytrap_1      | 08:59:59.920 honeytrap/server ▶ INFO 006 Configured port tcp/:8023
honeytrap_1      | 08:59:59.921 honeytrap/server ▶ INFO 007 Configured port tcp/:5900
honeytrap_1      | 08:59:59.922 honeytrap/server ▶ WARN 008 Unrecognized keys in configuration: [service.telnet.image service.telnet.server-name]
honeytrap_1      | 08:59:59.923 listeners/socket ▶ INFO 009 Listener started: tcp/:8022
honeytrap_1      | 08:59:59.926 listeners/socket ▶ INFO 00a Listener started: tcp/:8023
honeytrap_1      | 08:59:59.926 listeners/socket ▶ INFO 00b Listener started: tcp/:5900
honeytrap_1      | 08:59:59.945 web ▶ INFO 00c Web interface started: 127.0.0.1:8089

Thanks for any help, it looks like a great project

### PR DESCRIPTION
**Pull request by CapacitorSet**
Fixes #414.

### CODE REVIEW

**Comment by nl5887** [comment]
Actually I wanted to have the docker run standalone. Maybe better to create a `config-docker-agent-server` config.

**Comment by CapacitorSet** [comment]
In honeytrap-configs, you mean?

**Comment by nl5887** [comment]
Exactly. Think we should remove the configs from this repo, and move everything to the config repo.

**Comment by CapacitorSet** [comment]
It seems to be [already there](https://github.com/honeytrap/honeytrap-configs/tree/master/agent-server), and fixed. I'll edit my issue in honeytrap-docs and make a PR for removing the files.

**Pull request closed without merging**
