### PR TITLE
pushers: add rabbitmq

### LINKED ISSUE #254: channels: implement RabbitMQ
I'll do this, I just opened the issue to keep track of it.

### PR DESCRIPTION
**Pull request by CapacitorSet**
Fixes #254.

Pushes JSON messages to a configurable RabbitMQ queue.

Example config:

```toml
[channel.rabbitmq]
type="rabbitmq"
address="amqp://guest:guest@localhost:5672/"
queue="honeytrap"
```

### CODE REVIEW

**Comment by nl5887** [comment]
Seems to be missing `github.com/streadway/amqp` package.

**Comment by CapacitorSet** [comment]
https://travis-ci.org/honeytrap/honeytrap/jobs/365278898#L790

I think it's because `go get` automatically finds the import and downloads the dependency, so it doesn't need to be specified explicitly (unlike eg. with godep).

**Comment by CapacitorSet** [comment]
I ran `dep ensure`, but now it doesn't compile because of an error in the canary code:

```
$ go build -v
github.com/honeytrap/honeytrap/event
github.com/honeytrap/honeytrap/vendor/github.com/glycerine/rbuf
github.com/honeytrap/honeytrap/listener/canary/arp
github.com/honeytrap/honeytrap/listener/canary/ethernet
github.com/honeytrap/honeytrap/listener/canary/icmp
github.com/honeytrap/honeytrap/listener/canary/tcp
github.com/honeytrap/honeytrap/pushers
github.com/honeytrap/honeytrap/director/lxc
github.com/honeytrap/honeytrap/director
github.com/honeytrap/honeytrap/listener
github.com/honeytrap/honeytrap/director/forward
github.com/honeytrap/honeytrap/listener/agent
github.com/honeytrap/honeytrap/listener/canary
github.com/honeytrap/honeytrap/listener/socket
github.com/honeytrap/honeytrap/listener/netstack
# github.com/honeytrap/honeytrap/listener/canary
listener/canary/canary_linux.go:984:23: c.buffer.ReadUint32 undefined (type *rbuf.FixedSizeRingBuf has no field or method ReadUint32)
```

I'll look into that later.

**Comment by CapacitorSet** [comment]
Fixed.

**Comment by nl5887** [comment]
Looked up the ReadUint32 code, this is the original code:

```
func (b *FixedSizeRingBuf) ReadUint32() (uint32, error) {
        buff := [2]byte{}

        _, err := b.ReadAndMaybeAdvance(buff[:], true)
        if err != nil {
                return 0, err
        }

        return uint32(buff[0])<<8 + uint32(buff[1]), nil
}
```

Looks like that the ReadUint32 reads a Uint16 and casts it to a Uint32.

**Comment by CapacitorSet** [comment]
Whoops, I'll fix that.

**Comment by CapacitorSet** [comment]
Fixed.

**Comment by nl5887** [comment]
merged

**Pull request closed without merging**
