### PR TITLE
fix typos in function documentation for the udp handlers

### PR DESCRIPTION
**Pull request by picatz**
Was reading through the code and noticed the function documentation was little off in the UDP handler section. I figured I could help fix that pretty easily.

🤷‍♂️ And, yeah, I have a typo in my commit to fix some typo(s). It's like 4 in the morning though.

### CODE REVIEW

**Comment by nl5887** [comment]
Hahaha, thanks! Much appreciated.

**Comment by nl5887** [comment]
@picatz could you sign the CLA?

**Comment by picatz** [comment]
@nl5887 Signed 👍

**Comment by nl5887** [comment]
Much appreciated! Thanks for your help.

**Pull request merged**
